---
# tasks file for criecm.zfs
- name: OS vars
  include_tasks: '{{ includefile }}'
  with_first_found:
    - files:
        - "{{ ansible_facts['os_family'] }}.yml"
  loop_control:
    loop_var: includefile
  tags: vars,zfs

- name: get zpools
  command: 'zpool list -H -o name'
  changed_when: False
  check_mode: False
  register: zpools
  tags: vars,zfs

- name: replication hosts
  include_tasks: zfs_backup.yml
  loop_control:
    loop_var: backup_host
    label: '{{ backup_host }}'
  with_items: '{{ (shares + group_shares) | selectattr("zfsrc","defined") | selectattr("backup_on","defined") | map(attribute="backup_on") | map("regex_replace","^.*@","") | list | unique }}'
  tags: zfs,replication
  when: not restore
  register: replhosts

- name: PRA hosts
  include_tasks: zfs_pra.yml
  loop_control:
    loop_var: pra_host
    label: '{{ pra_host }}'
  with_items: '{{ (shares + group_shares) | selectattr("zfsrc","defined") | selectattr("pra_on","defined") | map(attribute="pra_on") | map("regex_replace",":.*$","") | list | unique }}'
  tags: zfs,pra
  when: not restore
  register: prahosts

- name: zfs_sync hosts
  include_tasks: zfs_sync.yml
  loop_control:
    loop_var: sync_host
    label: '{{ sync_host }}'
  with_items: '{{ (shares + group_shares) | selectattr("zfsrc","defined") | selectattr("sync_on","defined") | map(attribute="sync_on") | flatten | map("regex_replace",":.*$","") | unique }}'
  tags: zfs,sync
  when: not restore
  register: synchosts

- name: zfs shares
  include_tasks: zfs.yml
  with_items: '{{ (shares + group_shares) | selectattr("zfsrc","defined") | list }}'
  loop_control:
    loop_var: onezfs
  tags: zfs
  when: myzfs | length == 0 or myzfs == onezfs.name

- name: zfs snapshots
  include_tasks: zfs_snap.yml
  when: restore
  tags: zfs,snap
